#!/usr/bin/env python
"""Fill in the phoneme field for every phrase in the Workplace Language Bank.

    python -m scripts.generate_phonemes            # dry run, shows what changes
    python -m scripts.generate_phonemes --write    # write into the source files

Writes into the COMPACT SOURCE in packages/content/phrases, not into the built
output, so the phonemes are version-controlled, reviewable in a diff, and
regenerated by the normal content build like everything else.

Phonemes feed forced alignment, which feeds GOP. A wrong phoneme string produces
a confident and completely bogus pronunciation score, so the report flags every
word that fell back to the neural model rather than CMUdict — those are the ones
worth a human glance.
"""

from __future__ import annotations

import argparse
import json
import sys
from functools import lru_cache
from pathlib import Path


def repository_root() -> Path:
    for directory in Path(__file__).resolve().parents:
        if (directory / "package.json").exists() and (directory / "packages").is_dir():
            return directory
    raise SystemExit("Could not locate the repository root")


PHRASE_DIR = repository_root() / "packages" / "content" / "phrases"


@lru_cache(maxsize=1)
def _cmudict() -> dict:
    """The CMU pronouncing dictionary, loaded once.

    Constructing G2p() per word loads its neural fallback model each time and
    turns a two-second job into an unbounded one.
    """
    from pipeline.g2p import _backend

    return _backend().cmu


def in_cmudict(word: str) -> bool:
    """Whether CMUdict knows this word, or g2p_en had to guess it."""
    return word.lower() in _cmudict()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write the files")
    parser.add_argument("--force", action="store_true", help="regenerate existing phonemes")
    args = parser.parse_args()

    try:
        from pipeline.g2p import phoneme_string
    except Exception as error:  # noqa: BLE001
        print(f"G2P unavailable: {error}", file=sys.stderr)
        return 1

    total = 0
    generated = 0
    guessed_words: set[str] = set()

    for path in sorted(PHRASE_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        changed = False

        for entry in data["entries"]:
            total += 1
            if entry.get("phonemes") and not args.force:
                continue

            entry["phonemes"] = phoneme_string(entry["text"])
            generated += 1
            changed = True

            for word in _words(entry["text"]):
                if not in_cmudict(word):
                    guessed_words.add(word)

        if changed and args.write:
            # Keep one entry per line: the compact format exists so a reviewer
            # can read the whole corpus, and pretty-printing would destroy that.
            path.write_text(_render(data), encoding="utf-8")
            print(f"  wrote {path.name}")

    print(f"\n{generated} of {total} phrases phonemised")

    if guessed_words:
        print(
            f"\n{len(guessed_words)} words were NOT in CMUdict and were guessed by the "
            "neural fallback.\nThese are the ones worth checking by ear:\n"
        )
        for word in sorted(guessed_words):
            print(f"  {word}")

    if not args.write:
        print("\nDry run. Re-run with --write to apply.")

    return 0


def _words(text: str) -> list[str]:
    return [w.strip(".,!?;:'\"").lower() for w in text.split() if w.strip(".,!?;:'\"")]


def _render(data: dict) -> str:
    """Re-emit the compact format: one entry per line."""
    lines = [
        "{",
        f'  "slug": {json.dumps(data["slug"])},',
        f'  "title": {json.dumps(data["title"])},',
        f'  "target": {data["target"]},',
        '  "entries": [',
    ]

    rendered = [f"    {json.dumps(entry, ensure_ascii=False)}" for entry in data["entries"]]
    lines.append(",\n".join(rendered))
    lines += ["  ]", "}", ""]

    return "\n".join(lines)


if __name__ == "__main__":
    sys.exit(main())
